name: Sync to AccountB and Deploy Vercel
on:
  push:
    branches: [main]
jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to AccountB
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCOUNT_B_TOKEN }}
          repository: HoangGymscode/portfolio
          branch: main
          force: true

      - name: Trigger Vercel Deploy
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy?projectId=9JLjNex7wM9xh5mMaddRQBv5KQ8m" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
